### ISSUE TITLE
Add Spanish Language to YGOMobile?

### ISSUE THREAD

**Issue by VaHReX** [fallenstardust/YGOMobile-cn-ko-en#110]
Hello, first of all, congratulate you for the great work you are doing so that we can have this wonderful apk and share a pleasant time among nakamas playing YGO, I have a proposal for you:
For some time I have been working on the translation of the YGOMobile cards into Spanish, every time they release an update of the game, I rely on the DataEditorX app and I translate the cards so that all Spanish-speakers who have access to the game can enjoy it We put this translated file in the expansions folder of the game and that's it, now, I would like to know if there is a possibility that I can support them so that the game comes with the option to choose the Spanish language by default, as they did with English or the Korean, I am in complete disposition to support you in that and I know that everyone here in Latin America and the rest of the world where Spanish is spoken will appreciate it, best regards and I keep up to date!!!

**Comment by zhuhongbozhuhongbo** [comment]
Thanks for your kindness, We do want to add new languages to YGOMobile, but the limited energy constrained our progress. We would appreciate it if you have willing to join us. The configuration files and database of the game need to be updated frequently, which is a bit heavy. If you are sure to initiate this task, let's discuss how exactly we'll do that.

**Comment by fallenstardust** [comment]
would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?

**Comment by zhuhongbozhuhongbo** [comment]
Until now our documentation is nearly all Chinese, emmm can you build a YGOMobile app from the source code?

**Comment by zhuhongbozhuhongbo** [comment]
> Hello, first of all, congratulate you for the great work you are doing so that we can have this wonderful apk and share a pleasant time among nakamas playing YGO, I have a proposal for you: For some time I have been working on the translation of the YGOMobile cards into Spanish, every time they release an update of the game, I rely on the DataEditorX app and I translate the cards so that all Spanish-speakers who have access to the game can enjoy it We put this translated file in the expansions folder of the game and that's it, now, I would like to know if there is a possibility that I can support them so that the game comes with the option to choose the Spanish language by default, as they did with English or the Korean, I am in complete disposition to support you in that and I know that everyone here in Latin America and the rest of the world where Spanish is spoken will appreciate it, best regards and I keep up to date!!!

Sorry, I'm so sorry for not noticing your issue in time

**Comment by VaHReX** [comment]
Ok, I am completely ready for that, I have already updated the cards.cdb database file to 100% Spanish, now I am translating the strings.conf file, which I should be finishing soon. What I would like to know is what this process would be like here on GitHub and the app they use to edit the CDB, I use DataXEditor

**Comment by VaHReX** [comment]
> Thanks for your kindness, We do want to add new languages to YGOMobile, but the limited energy constrained our progress. We would appreciate it if you have willing to join us. The configuration files and database of the game need to be updated frequently, which is a bit heavy. If you are sure to initiate this task, let's discuss how exactly we'll do that.

Ok, I am completely ready for that, I have already updated the cards.cdb database file to 100% Spanish, now I am translating the strings.conf file, which I should be finishing soon. What I would like to know is what this process would be like here on GitHub and the app they use to edit the CDB, I use DataXEditor

**Comment by VaHReX** [comment]
> would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?

Like I would, I'm new to this HitHub thing haha

**Comment by VaHReX** [comment]
> Until now our documentation is nearly all Chinese, emmm can you build a YGOMobile app from the source code?

I would have to try, I have never used android studio but I would have to see

**Comment by fallenstardust** [comment]
> > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> 
> Like I would, I'm new to this HitHub thing haha

you can add cards.cdb to https://github.com/mycard/ygopro-database.git

**Comment by zhuhongbozhuhongbo** [comment]
My email is 1076306278@qq.com. The comment is not convenient, I advice we communicate via email if you agree. I'll introduce our works and how to collaborate.

**Comment by VaHReX** [comment]
> > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > 
> > 
> > Like I would, I'm new to this HitHub thing haha
> 
> you can add cards.cdb to https://github.com/mycard/ygopro-database.git

How i can do that??? I try but nothing is happen

**Comment by VaHReX** [comment]
> My email is [1076306278@qq.com](mailto:1076306278@qq.com). The comment is not convenient, I advice we communicate via email if you agree. I'll introduce our works and how to collaborate.

Gmail: jmcorderok1992@gmail.com

**Comment by fallenstardust** [comment]
> > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > 
> > > 
> > > Like I would, I'm new to this HitHub thing haha
> > 
> > 
> > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> 
> How i can do that??? I try but nothing is happen



> > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > 
> > > 
> > > Like I would, I'm new to this HitHub thing haha
> > 
> > 
> > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> 
> How i can do that??? I try but nothing is happen

you can fork this repository and add your cards.cdb and strings.conf in Spanish. push them on your github and start a pull request on website of the upstream repository. welcome!

by the way. why you want to add Spanish data to my project? dont you use ygoproES or edopro? as you see, ygomobile is a application for OCG players. it follows ocgcore.

**Comment by VaHReX** [comment]
> > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > 
> > > > 
> > > > Like I would, I'm new to this HitHub thing haha
> > > 
> > > 
> > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > 
> > 
> > How i can do that??? I try but nothing is happen
> 
> > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > 
> > > > 
> > > > Like I would, I'm new to this HitHub thing haha
> > > 
> > > 
> > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > 
> > 
> > How i can do that??? I try but nothing is happen
> 
> you can fork this repository and add your cards.cdb and strings.conf in Spanish. push them on your github and start a pull request on website of the upstream repository. welcome!
> 
> by the way. why you want to add Spanish data to my project? dont you use ygoproES or edopro? as you see, ygomobile is a application for OCG players. it follows ocgcore.

Yeap, we use EDOPro, but we also like to use the YGOMobile, the YGOProES is discontinued, its developer has not supported it for 4 years, we are a large community that uses the ygomobile and that is why my desire to support your project and add the Spanish language to him, the work you have been doing all these years with the game is great, and we appreciate it very much, many repeated thanks.

**Comment by fallenstardust** [comment]
> > > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > > 
> > > > > 
> > > > > Like I would, I'm new to this HitHub thing haha
> > > > 
> > > > 
> > > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > > 
> > > 
> > > How i can do that??? I try but nothing is happen
> > 
> > 
> > > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > > 
> > > > > 
> > > > > Like I would, I'm new to this HitHub thing haha
> > > > 
> > > > 
> > > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > > 
> > > 
> > > How i can do that??? I try but nothing is happen
> > 
> > 
> > you can fork this repository and add your cards.cdb and strings.conf in Spanish. push them on your github and start a pull request on website of the upstream repository. welcome!
> > by the way. why you want to add Spanish data to my project? dont you use ygoproES or edopro? as you see, ygomobile is a application for OCG players. it follows ocgcore.
> 
> Yeap, we use EDOPro, but we also like to use the YGOMobile, the YGOProES is discontinued, its developer has not supported it for 4 years, we are a large community that uses the ygomobile and that is why my desire to support your project and add the Spanish language to him, the work you have been doing all these years with the game is great, and we appreciate it very much, many repeated thanks.

have you receive my email?

**Comment by VaHReX** [comment]
> > > > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > > > 
> > > > > > 
> > > > > > Like I would, I'm new to this HitHub thing haha
> > > > > 
> > > > > 
> > > > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > > > 
> > > > 
> > > > How i can do that??? I try but nothing is happen
> > > 
> > > 
> > > > > > > would you send a pull request to show translated strings.conf,bot.conf,strings.xml(espanol)?
> > > > > > 
> > > > > > 
> > > > > > Like I would, I'm new to this HitHub thing haha
> > > > > 
> > > > > 
> > > > > you can add cards.cdb to https://github.com/mycard/ygopro-database.git
> > > > 
> > > > 
> > > > How i can do that??? I try but nothing is happen
> > > 
> > > 
> > > you can fork this repository and add your cards.cdb and strings.conf in Spanish. push them on your github and start a pull request on website of the upstream repository. welcome!
> > > by the way. why you want to add Spanish data to my project? dont you use ygoproES or edopro? as you see, ygomobile is a application for OCG players. it follows ocgcore.
> > 
> > 
> > Yeap, we use EDOPro, but we also like to use the YGOMobile, the YGOProES is discontinued, its developer has not supported it for 4 years, we are a large community that uses the ygomobile and that is why my desire to support your project and add the Spanish language to him, the work you have been doing all these years with the game is great, and we appreciate it very much, many repeated thanks.
> 
> have you receive my email?

Here are the screenshots, look at the number of pages they have depending on the resolution of DataEditorX, I already published the error in the official group of the application but they have not given me a response, I use a very obsolete version and it is the one that is helping me solve for now, but I would like to be able to update it.
![349](https://github.com/fallenstardust/YGOMobile-cn-ko-en/assets/138526168/4b5ee18b-2d01-49d1-b7f2-c832932f7108)
![294](https://github.com/fallenstardust/YGOMobile-cn-ko-en/assets/138526168/b2657c5a-c32b-4a3e-9276-c41a91e0d475)

**Comment by VaHReX** [comment]
Now, I keep updating the cards.cdb and strings.conf files; To add the Spanish Language to the next update of the game (or when it is convenient or possible), should I fork the YGOMobile repository and translate the files that you indicated?
