### ISSUE TITLE
YGOMobile 在尝试与 AI 比赛时崩溃

### ISSUE THREAD

**Issue by VaHReX** [fallenstardust/YGOMobile-cn-ko-en#144]
在大多数情况下，当尝试与人工智能对战时，游戏会崩溃并关闭，所有语言都会发生这种情况，以下是日志！
[【YGO】2024-02-19 00.11.30.log](https://github.com/fallenstardust/YGOMobile-cn-ko-en/files/14326669/YGO.2024-02-19.00.11.30.log)
[【YGO】2024-02-19 00.12.51.log](https://github.com/fallenstardust/YGOMobile-cn-ko-en/files/14326670/YGO.2024-02-19.00.12.51.log)
[【YGO】2024-02-19 00.16.21.log](https://github.com/fallenstardust/YGOMobile-cn-ko-en/files/14326672/YGO.2024-02-19.00.16.21.log)

**Comment by fallenstardust** [comment]
when it happens

**Comment by VaHReX** [comment]
> how to operate to recurrent the error？

playing vs the AI, the error is shown to you in most cases, you choose the AI vs the one you want to play (using any language), and as soon as you start, the game closes showing the message that YGOMobile stopped working, or also after him rock, paper, scissors
![image](https://github.com/fallenstardust/YGOMobile-cn-ko-en/assets/138526168/577875a0-8935-4954-989f-e12a83fdeb99)

**Comment by VaHReX** [comment]
every time I try to play VS the AI
________________________________
De: fallenstardust ***@***.***>
Enviado: martes, 20 de febrero de 2024 07:12
Para: fallenstardust/YGOMobile-cn-ko-en ***@***.***>
Cc: Dark Zane ***@***.***>; Author ***@***.***>
Asunto: Re: [fallenstardust/YGOMobile-cn-ko-en] YGOMobile 在尝试与 AI 比赛时崩溃 (Issue #144)


when it happens

―
