### ISSUE TITLE
libWindbot.aar is outdated

### ISSUE THREAD

**Issue by Yuzurisa** [fallenstardust/YGOMobile-cn-ko-en#33]
The aar in repo https://github.com/mercury233/libwindbot is too outdated. The latest release of it failed load the new Red-Eyes AI.
I wonder how the official release of YGOMobile was made. Isn't it public? If it is, could you provide the latest build of it? I badly need that file to distribute my release. Thanks!

**Comment by fallenstardust** [comment]
你可以发issue给libwindbot仓库的主要管理者敦促一份released aar
如果你真的关注official release of ygomobile，它当然是public的

**Comment by mercury233** [comment]
sorry for any inconvenience, I just published the release of libwindbot. and you can build it on your own (but E4K may won't wont too well and needs some hack to fix it)
