### ISSUE TITLE
Add 7210 back to server list

### ISSUE THREAD

**Issue by purerosefallen** [fallenstardust/YGOMobile-cn-ko-en#34]
For some reasons, the 7210 server would no longer insert cards before the MyCard or 233 release. I believe it would be reasonable enough to put this server back to the server list.
Now that many people in YGOPro community have no knowledge of 7210 server, could you add this server back to server list to make the players more convenient to join in this server? Thanks!

**Comment by fallenstardust** [comment]
7210 server has its own android client edition with different ocgcore and released ver name.
