### ISSUE TITLE
Incorporate something new in the mobile version

### ISSUE THREAD

**Issue by Termita** [fallenstardust/YGOMobile-cn-ko-en#44]
Good morning, is there the possibility of incorporating the pc option where when writing "L" in the password it loads the list of rooms created? I find it a very interesting option. If you could tell me what is the method that does this and where it should be applied, I could do it. Thank you

**Comment by fallenstardust** [comment]
some servers' special editon has such function but not basic edition like mine. you should ask servers' managers. not me.

**Comment by Termita** [comment]
I have a server with this function implemented, however something is missing in the ygopro code for mobile to load the list. I meant that if you could add this code, since the pc version has it.
