### ISSUE TITLE
Instant crash of 3.7.9

### ISSUE THREAD

**Issue by tiendatbinhan** [fallenstardust/YGOMobile-cn-ko-en#45]
Hello.
I'm writing to report a new problem of 3.7.9 version of ygomobile.
The 3.7.7 version worked fine for me, but after updating to 3.7.9, the system said that ygomobile was forced to close.
Looking forward to receiving your feedback and/or solution.
Regards.

**Comment by tiendatbinhan** [comment]
The issue was only appeared in the EN version, the other version works fine, but I can't read neither Chinese nor Koreans 👎

**Comment by Textilfrenzy** [comment]
Be patient. The devs have their own lives as well. I did reported the same issue to them and im sure they will fix the problem as soon as they can :)

**Comment by fallenstardust** [comment]
can you send a screenshoot while crashed or log？

**Comment by tiendatbinhan** [comment]
I have already recorded the crash, and there you go. Watch this record: https://drive.google.com/file/d/1EMtuF9M7wErA5fMk1bKQNuu-ZFZildvj/view?usp=drivesdk

**Comment by fallenstardust** [comment]
i fixed this problem. you can redownload:
https://www.pgyer.com/ygomobileen
and help me tell other users, thx alot

**Comment by tiendatbinhan** [comment]
Thank you for taking my issue into consideration.
