### ISSUE TITLE
I can't backup the decks

### ISSUE THREAD

**Issue by Termita** [fallenstardust/YGOMobile-cn-ko-en#46]
After compiling, when trying to backup the decks it throws an error.

"java.io.FileNotFoundException: /storage/emulated/0/ygocore/deck/Agua.ydk:open failed: ENOENT (No such file or directory)"

Another thing I would like to know if you can support me, is there a way to control the automatic updates? is that it is traditional for the Latino community and a group of players who use a smaller card data. Is it possible that we can have control or send our own updates? because when you send an update everyone receives everything in Chinese hehehehe

**Comment by zjw-swun** [comment]
Another way, you can learn Chinese
