### ISSUE TITLE
apk安装后图包pics.zip没有解压，pics是一个空文件夹

### ISSUE THREAD

**Issue by Kkyoyo** [fallenstardust/YGOMobile-cn-ko-en#56]
图包和脚本无法加载，俩个压缩包都没有解压，对应的文件夹都是空的，其他都正常，手机系统是Android10。  
安卓萌新不知道怎么处理
rt，求助各位大佬

**Comment by mercury233** [comment]
那些是不需要解压的，运行时会动态加载

**Comment by Kkyoyo** [comment]
> 

感谢回复，发现问题了，因为我是用pc的图包打包的，图太大了加载不出来，谢谢大佬的帮助
