### ISSUE TITLE
Feat req: use versioning in card pic download

### ISSUE THREAD

**Issue by purerosefallen** [fallenstardust/YGOMobile-cn-ko-en#91]
To avoid wrong cache, please add versioning in card image download, rather asking MyCard staff cleaning CDN cache for you, as we often running into trouble designing the CDN system especially for you.
eg. GET `https://cdn02.moecube.com:444/ygomobile-images/70155677.jpg?version=3.0.0` as cache differs for each combination of URL params.

**Comment by fallenstardust** [comment]
tln
