### ISSUE TITLE
How to build a game

### ISSUE THREAD

**Issue by IntinteDAO** [fallenstardust/YGOMobile-cn-ko-en#93]
Welcome.

I am the developer of the alternative to YGO game "Summoned Monsters". The aim was to create a game inspired by the classic Yu-Gi-Oh installments, but under a free licence.

I have made the game, although I now want to do an "upgrade" to make the production even better.

I used to write a script that compiled YGOMobile, but unfortunately either it stopped working or I'm doing something wrong because I'm not able to build the game. Maybe I used to use an older system or a similar thing will work, but it seems to me that the Android NDK is system independent (in the sense that it provides the correct compiler itself and so on).

Unfortunately, I don't speak Chinese and can't fully understand the instructions.

https://0bin.net/paste/3dxkfu5k#qsWU8Y3Sp4cJZPf1DtPSxQWKruHAtEts9dGieXqSLvD

Script:
https://0bin.net/paste/0IPdSRuu#nWL0urFcw6emrN4EU5RghX5al+A5O9vlhwQzovVLkW5

**Comment by fallenstardust** [comment]
could you email me with screenshoots? 
905309599@qq.com

**Comment by IntinteDAO** [comment]
> could you email me with screenshoots? [905309599@qq.com](mailto:905309599@qq.com)

Well, I compiled id successfully, closing :P

Here if someone read have a script to do this with Summoned Monsters. I still need to compile my own Libwindbot, but maybe one day ...

https://github.com/IntinteDAO/Summoned-Monsters/blob/master/build/android-build.sh
